Subject_ID = "Test"

[Processing_Parameters]
behavior_offset = 0.0
final_z = "true"
z_window = 60.0
bandpass_bandwidth = 0.0
sampling_frequency = 1000.0
downsample_frequency = 1000.0
transform = "spectrogram"
no_per_segment = 216
no_overlap = 108

[Signal_Indices]
total_channels = 8

[Processing_Parameters.left]
carrier_frequency_g = 100.0
carrier_frequency_r = 100.0

[Processing_Parameters.right]
carrier_frequency_g = 100.0
carrier_frequency_r = 100.0

[Signal_Indices.left]
photom_g = 0
photom_r = 1
carrier_g = 2
carrier_r = 3

[Signal_Indices.right]
photom_g = 0
photom_r = 1
carrier_g = 2
carrier_r = 3

[Signal_Indices.left.emission_wavelength]
green = 10.0
red = 10.0

[Signal_Indices.left.excitation_wavelength]
green = 10.0
red = 10.0

[Signal_Indices.left.sensor_protein]
green = "gcamp"
red = "rcamp"

[Signal_Indices.right.emission_wavelength]
green = 10
red = 10

[Signal_Indices.right.excitation_wavelength]
green = 10
red = 10

[Signal_Indices.right.sensor_protein]
green = "gcamp"
red = "rcamp"
