# docker-compose -f ./docker/docker-compose-standard_worker.yaml up -d --build 
version: '2.4'
services:
  standard_worker:
    build:
      # only necessary if rebuilding image
      context: .
      dockerfile: ./standard_worker.Dockerfile
      args:
        - PY_VER
        - DEPLOY_KEY
        - WORKER_BASE_HASH
        - REPO_OWNER
        - REPO_NAME
    image: registry.vathes.com/sciops/standard_${REPO_NAME}:py${PY_VER}-${DIST}-${WORKFLOW_VERSION}
    environment:
      - CONTAINER_USER
      - DJ_HOST
      - DJ_USER
      - DJ_PASS
      - DATABASE_PREFIX
      - AWS_ACCESS_KEY
      - AWS_ACCESS_SECRET
      - EPHYS_ROOT_DATA_DIR=/home/${CONTAINER_USER}/inbox
      - EPHYS_PROCESSED_DATA_DIR=/home/${CONTAINER_USER}/outbox
    volumes:
      - ${ROOT_DATA_DIR}:/home/${CONTAINER_USER}/inbox
      - ${PROCESSED_DATA_DIR}:/home/${CONTAINER_USER}/outbox
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
    scale: ${WORKER_COUNT:-1}
    command:
      - /bin/bash
      - -c
      - |
        run_workflow standard_worker &
        tail -f /dev/null
